name: validate

on:
  push:
  pull_request:

jobs:
  windows-powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate release
        shell: powershell
        run: .\tests\validate.ps1
